---
SLE_15:
  beta: true
  online_migration_targets: []
  base_product:
    repositories:
    - SUSE_Linux_Enterprise_Server_15_x86_64:SLE-Product-SLES15-Pool
    - SUSE_Linux_Enterprise_Server_15_x86_64:SLE-Product-SLES15-Updates
  paid_extension:
    identifier: sle-ha/15/x86_64
  free_extension:
    identifier: sle-module-basesystem/15/x86_64
    credentials_file: /etc/zypp/credentials.d/Basesystem_Module_15_x86_64
    service: Basesystem_Module_15_x86_64
    release_package: sle-module-basesystem-release
    repositories:
    - Basesystem_Module_15_x86_64:SLE-Module-Basesystem15-Debuginfo-Pool
    - Basesystem_Module_15_x86_64:SLE-Module-Basesystem15-Debuginfo-Updates
    - Basesystem_Module_15_x86_64:SLE-Module-Basesystem15-Pool
    - Basesystem_Module_15_x86_64:SLE-Module-Basesystem15-Source-Pool
    - Basesystem_Module_15_x86_64:SLE-Module-Basesystem15-Updates

SLE_12_SP3:
  beta: false
  online_migration_targets:
  - SLES12-SP4
  next_version: SLES12-SP4
  base_product:
    repositories:
    - SUSE_Linux_Enterprise_Server_12_SP3_x86_64:SLES12-SP3-Pool
    - SUSE_Linux_Enterprise_Server_12_SP3_x86_64:SLES12-SP3-Updates
    - SUSE_Linux_Enterprise_Server_12_SP3_x86_64:SLES12-SP3-Debuginfo-Updates
  paid_extension:
    identifier: sle-ha/12.3/x86_64
  free_extension:
    identifier: sle-sdk/12.3/x86_64
    credentials_file: /etc/zypp/credentials.d/SUSE_Linux_Enterprise_Software_Development_Kit_12_SP3_x86_64
    service: SUSE_Linux_Enterprise_Software_Development_Kit_12_SP3_x86_64
    release_package: sle-sdk-release
    repositories:
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_SP3_x86_64:SLE-SDK12-SP3-Pool
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_SP3_x86_64:SLE-SDK12-SP3-Updates

SLE_12_SP2:
  beta: false
  online_migration_targets:
  - SLE-HPC-12-SP3
  - SLES12-SP3
  - SLES12-SP4
  base_product:
    repositories:
    - SUSE_Linux_Enterprise_Server_12_SP2_x86_64:SLES12-SP2-Pool
    - SUSE_Linux_Enterprise_Server_12_SP2_x86_64:SLES12-SP2-Updates
    - SUSE_Linux_Enterprise_Server_12_SP2_x86_64:SLES12-SP2-Debuginfo-Updates
  paid_extension:
    identifier: sle-ha/12.2/x86_64
  free_extension:
    identifier: sle-sdk/12.2/x86_64
    credentials_file: /etc/zypp/credentials.d/SUSE_Linux_Enterprise_Software_Development_Kit_12_SP2_x86_64
    service: SUSE_Linux_Enterprise_Software_Development_Kit_12_SP2_x86_64
    release_package: sle-sdk-release
    repositories:
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_SP2_x86_64:SLE-SDK12-SP2-Pool
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_SP2_x86_64:SLE-SDK12-SP2-Updates

SLE_12_SP1:
  beta: false
  online_migration_targets:
  - SLE-HPC-12-SP2
  - SLE-HPC-12-SP3
  - SLES12-SP2
  - SLES12-SP3
  - SLES12-SP4
  base_product:
    repositories:
    - SUSE_Linux_Enterprise_Server_12_SP1_x86_64:SLES12-SP1-Pool
    - SUSE_Linux_Enterprise_Server_12_SP1_x86_64:SLES12-SP1-Updates
    - SUSE_Linux_Enterprise_Server_12_SP1_x86_64:SLES12-SP1-Debuginfo-Updates
  paid_extension:
    identifier: sle-ha/12.1/x86_64
  free_extension:
    identifier: sle-sdk/12.1/x86_64
    credentials_file: /etc/zypp/credentials.d/SUSE_Linux_Enterprise_Software_Development_Kit_12_SP1_x86_64
    service: SUSE_Linux_Enterprise_Software_Development_Kit_12_SP1_x86_64
    release_package: sle-sdk-release
    repositories:
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_SP1_x86_64:SLE-SDK12-SP1-Pool
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_SP1_x86_64:SLE-SDK12-SP1-Updates

SLE_12:
  beta: false
  online_migration_targets:
  - SLE-HPC-12-SP2
  - SLE-HPC-12-SP3
  - SLES12-SP1
  - SLES12-SP2
  - SLES12-SP3
  - SLES12-SP4
  base_product:
    repositories:
    - SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Pool
    - SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Updates
    - SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Debuginfo-Updates
  paid_extension:
    identifier: sle-ha/12/x86_64
  free_extension:
    identifier: sle-sdk/12/x86_64
    credentials_file: /etc/zypp/credentials.d/SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64
    service: SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64
    release_package: sle-sdk-release
    repositories:
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64:SLE-SDK12-Pool
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64:SLE-SDK12-Updates

FEDORA_24:
  beta: false
  online_migration_targets: []
  base_product:
    repositories:
    - SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Pool
    - SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Updates
    - SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Debuginfo-Updates
  paid_extension:
    identifier: sle-ha/12/x86_64
  free_extension:
    identifier: sle-sdk/12/x86_64
    credentials_file: /etc/zypp/credentials.d/SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64
    service: SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64
    release_package: sle-sdk-release
    repositories:
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64:SLE-SDK12-Pool
    - SUSE_Linux_Enterprise_Software_Development_Kit_12_x86_64:SLE-SDK12-Updates
